### ISSUE TITLE
Problems with HTTPS

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/ComplexViewer#121] opened 2017-10-02 14:10 UTC
We seem to have issues with `UniProt Curated Features` and `SuperFamily`, as they are not supporting HTTPS. 

The EBI forces from today every request to run over HTTPS: 
https://www.ebi.ac.uk/about/news/service-news/embl-ebi-be-https-default-1-october

I've contacted both resources, but it may take a bit until they answer.

**Comment by bmeldal** [comment] 2017-10-02 14:36
Yup, that was my question on Friday. I expected that. I hope you find a solution.

**Comment by tschaka1904** [comment] 2017-10-02 15:49
The solution is that UniProt und SuperFamily follow the protocol or the viewer needs to pull the data somehow else.

**Comment by tschaka1904** [comment] 2017-10-02 16:01
I've talked to SuperFamily and they said that HTTPS is working. It seems like there is a little certificate issue though: 
![screen shot 2017-10-02 at 16 56 43](https://user-images.githubusercontent.com/5269116/31086959-4538d45c-a793-11e7-940d-1d04d4dd0a9c.png)

Might be worth looking into that. Haven't heard back from UniProt.

**Comment by tschaka1904** [comment] 2017-10-02 16:04
I think we need to amend this bit as well: 
https://github.com/MICommunity/ComplexViewer/blob/master/src/controller/xiNET_Storage.js#L121

**Comment by tschaka1904** [comment] 2017-10-03 08:52
> Hi Max,
> 
> I assume that you retrieve our page via an JS http request client side?
> Then you might be blocked because secure to insecure is not allowed in some
> browsers. In which case there is nothing we can do at this time.
> 
> You could introduce a proxy or use the db_fetch thing from EBI External
> Services.
> 
> Our HTTPS site is not ready yet (getting the right certificates is a bit of an
> hassle)
> 
> If you are doing it from the server then I have no idea why your code stopped
> working.
> 
> Regards,
> Jerven

**Comment by colin-combe** [comment] 2017-10-03 10:41
Duplicate of #99 ? I think we won't be able to contact web services on other servers directly after changing to https

**Comment by tschaka1904** [comment] 2017-10-03 11:08
I guess once UniProt has got the certificate it should be fine. And we update the URLs. I created a pull request with the updated SuperFamily URL.

**Comment by tschaka1904** [comment] 2017-10-03 15:25
Thank @colin-combe for merging it! It did the trick for SuperFamily! ...but, the data coming from the SuperFamily WS seems to vary a bit in speed. But it works. I would expect the same for UniProt, once they have their certificate.

**Comment by tschaka1904** [comment] 2017-10-03 15:25
I'll deploy the version soon to PROD.

**Comment by tschaka1904** [comment] 2017-10-05 15:57
SuperFamily is now working again in production! ;-)

**Comment by colin-combe** [comment] 2017-10-06 12:23
Cool; I guess I was wrong in what I said before... as long as they have https sorted out its fine.

**Comment by tschaka1904** [comment] 2017-10-13 13:18
Alright! I was talking to UniProt! The txt version of their results won't be available for some time. They are waiting for a certificate. But this service is supposed to deliver the same information: https://www.ebi.ac.uk/proteins/api/proteins/P69905

**Comment by colin-combe** [comment] 2017-10-13 14:39
OK, changed to use that https json service for uniprot data.
That version deployed at complexviewer.org for you to test.

There's an open pull request to merge those changes and also the changes to show the spinner for 2 seconds then show moving proteins (see #120, think that's the best we can do at moment).

**Comment by bmeldal** [comment] 2017-10-13 14:48
UniProt works!
I'm not sure the spinner-then-bouncing option is much better. Let's see what users are saying!

**Comment by colin-combe** [comment] 2017-11-03 15:06
I think this can be closed as now working with https

**Comment by bmeldal** [comment] 2017-11-03 15:13
Actually, it's broken again. It didn't work during the webinar on Wednesday and I forgot that it got fixed in the meantime. New ticket?

**Comment by colin-combe** [comment] 2017-11-03 15:32
No new ticket, reopening is better for continuation of same issue i think. 

The change that fixed this is not deployed in ComplexPortal (you can see it is still contacting an http rather than https address).

The change is also not merged into the MICommunity repo but is languishing in pull request #123

I can merge these into MICommunity repo now if you like?

**Comment by bmeldal** [comment] 2017-11-03 15:38
Thanks, Colin. Yes, please merge into MICommunity.

@noedelta can you update the version on the CP, please? Probably got forgotten with Max leaving and I tested the new version only on the demo site.

**Comment by colin-combe** [comment] 2017-11-03 15:47
OK, merged. 

(perhaps still some problems with the initial layout to be considered)

Will leave issue open until this is sorted out...

**Comment by bmeldal** [comment] 2017-11-03 15:48
@colin-combe yes leave open til it's updated in the CP.

**Comment by bmeldal** [comment] 2018-04-05 11:46
Working again.

**Closed by bmeldal** 2018-04-05 11:46 UTC
